CC=g++
FLAG=-Wall -std=c++17
EXE=memory_sim_test

all: $(EXE)

# TODO: complete this makefile such that it creates an executable named in $EXE with main.cpp and util.hpp on Linux or Mac.

clean:
	rm *.x *.o $(EXE)
