CC=g++
FLAG=-Wall -std=c++17
EXE=css342_quiz_swap_array

# TODO: Complete this makefile such that it creates an executable named in $EXE with main.cpp and util.hpp on Linux or Mac.

all: $(EXE)

main.o: # TODO
	# TODO

$(EXE): # TODO
	# TODO

clean:
	rm *.x *.o $(EXE)